FROM python:3.11.5
RUN apt update && apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install python-dotenv pypdf langchain chromadb==0.4.10 redis uvicorn fastapi tqdm duckduckgo_search openai==1.7.2 aiofiles python-multipart nest_asyncio openai-whisper==20231117 pydub moviepy -U langchain-community langchain-openai==0.0.2.post1 beautifulsoup4 alembic docx2txt langchainhub